server.port = 8080

spring.datasource.url=jdbc:mysql://localhost:3306/laptopshop_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1452003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

project.upload.dir.laptop=src/main/images/laptop
project.upload.dir.user=src/main/images/user
project.upload.dir.base=src/main/images